[general]
import = ["~/AppData/Roaming/alacritty/base.toml"]
working_directory = "C:\\code"

[font]
normal = { family = "Inconsolata Nerd Font" }
size = 12

[terminal.shell]
program = "pwsh.exe"

[keyboard]
bindings = [
    # Only use Ctrl+C for copy when text is selected; otherwise pass through
   { key = "Return", mods = "Shift", chars = "\u001b\r" },
]

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
mouse.enabled = true
hyperlinks = true
command = { program = "cmd", args = ["/C", "start", ""] }
