return {
  'nvim-treesitter/nvim-treesitter',
  lazy = false,
  build = ':TSUpdate',
  config = function()
    require('nvim-treesitter').install({
      'bash',
      'bp',
      'c',
      'cpp',
      'css',
      'diff',
      'dockerfile',
      'git_config',
      'gitcommit',
      'gitignore',
      'go',
      'html',
      'java',
      'javascript',
      'json',
      'kotlin',
      'lua',
      'make',
      'markdown',
      'ninja',
      'powershell',
      'proto',
      'python',
      'regex',
      'ruby',
      'rust',
      'sql',
      'textproto',
      'toml',
      'typescript',
      'vim',
      'xml',
      'yaml',
      'zsh',
    })
  end,
}
