" Use VIM settings, rather than Vi settings
set nocompatible

" Turn on filetype based plugins
filetype plugin on

" Turn on line numbers 
set nu

"Enable syntax highlighting
syntax on

" Auotmatically indent based on file type
filetype indent on
set autoindent

" Case insensitive search (smartcase)
set ignorecase smartcase

" Highlight search
set hls

" Wrap text instead of being on one line
set lbr

" Incremental search
set incsearch

" Remap Ctrl-N and Ctrl-P to :next and :previous, respectively
nnoremap <C-N> :next<Enter>
nnoremap <C-P> :previous<Enter>
set confirm

" Set indentation to spaces
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab


" Set go filetype
au BufNewFile,BufRead *.go setfiletype go

  " Set indentation for Python according to Google Style Guide
au FileType python set tabstop=4 shiftwidth=4 softtabstop=4 expandtab

  " Set indentation for Ruby according to Google Style Guide
au Filetype ruby set tabstop=2 shiftwidth=2 expandtab

  " Set indentation for C according to Google Style Guide
au Filetype c set tabstop=2 shiftwidth=2 expandtab

  " Set indentation for C++ according to Google Style Guide
au Filetype cpp set tabstop=2 shiftwidth=2 expandtab

  " Set indentention for Make files
au Filetype make set noexpandtab

  " Set indentation for Go files
au Filetype go setlocal noexpandtab tabstop=4 softtabstop=4

  " Set indentation for HTML files
au Filetype html set tabstop=2 shiftwidth=2 expandtab
au FileType xhtml set tabstop=2 shiftwidth=2 expandtab

  " Set settings for LaTeX files
au Filetype tex SPCheck
au Filetype tex let dialect='US'

" Ignore silly files
set wildignore=*.o,*.obj,*.bak,*.exe

" Set colorscheme
colorscheme molokai

" Set font
set gfn=Inconsolata\ 11

" Bind NERDTree commands
map <F2> :NERDTreeToggle<CR>
